<div class="order-card">
	<div class="order-header">
		<div class="order-subject"><?= $ctx['subject'] ?></div>
		<div class="order-time-created"><?= $ctx['time_created'] ?></div>
	</div>
	<div class="order-description"><?= $ctx['description'] ?></div>
	<div class="order-price">
		<span class="order-price-number"><?= $ctx['price'] ?></span>
		<span class="order-price-currency">руб.</span>
	</div>
</div>