<h3>Список заказов</h3>

<? if (empty($ctx['orders'])): ?>
	<p>
		<span>Пока что еще никаких заказов нет..</span> <span>Можно <a href="/neworder">Создать</a></span>
	</p>
<? else: ?>
	<div class="orders-list">
		<? foreach ($ctx['orders'] as $order) : ?>
			<div class="orders-list-item">
				<?= \View\widget('order', 'card', ['order' => $order]); ?>
			</div>
		<? endforeach ?>
	</div>
<? endif ?>