<html>
	<head>
		<title>Система заказов</title>
		<meta charset="utf-8"/>
		<link rel="stylesheet" href="/css/layout.css" />
		<link rel="stylesheet" href="/css/form.css" />
		<link rel="stylesheet" href="/css/order.css" />
		<link rel="stylesheet" href="/css/common.css" />
		<link rel="stylesheet" href="/css/order/list.css" />
		<link rel="stylesheet" href="/css/order/card.css" />

		<link rel="stylesheet" href="/css/jquery-ui.min.css"/>
		<? // TODO Это все, конечно, надо подключать через менеджеры статики, учитывать зависимости и т.п., но долго ?>
		<script type="text/javascript" src="/js/jquery.js"></script>
		<script type="text/javascript" src="/js/jquery-ui.min.js"></script>
		<script type="text/javascript" src="/js/jquery.form.js"></script>
		<script type="text/javascript" src="/js/common.js"></script>
		<script type="text/javascript" src="/js/ajax-form.js"></script>
		<script type="text/javascript" src="/js/ajax-redirect.js"></script>
		<script type="text/javascript" src="/js/ajax-error.js"></script>
		<script type="text/javascript" src="/js/navigator.js"></script>
		<script type="text/javascript" src="/js/large-text-toggle.js"></script>
		<script type="text/javascript" src="/js/orders.js"></script>
		<script type="text/javascript" src="/js/account.js"></script>
	</head>

	<body>
		<div class="container">
			<div class="header">
				<a href="/" title="Simple Freelance System">
					<div class="logo">SFS</div>
				</a>

				<? if ($currentUser = \Session\getCurrentUser()) : ?>
					<div class="current-user">
						<div class="current-user-account"><?= $currentUser['money'] ?> р.</div>

						<div class="current-user-name"><?= $currentUser['name'] ?></div>
						<div class="current-user-logout-link">
							<a href="/logout">Выйти</a>
						</div>
					</div>
				<? endif ?>
			</div>

			<div class="navigation-bar">
				<div class="main-menu">
					<? if ($currentUser) : ?>
						<div class="main-menu-item">
							<a class="main-menu-item-link-text" href="/">
								Заказы
							</a>
						</div>
						<? if (\User\canCreateOrders()): ?>
							<div class="main-menu-item">
								<a class="main-menu-item-link-text" href="/neworder">
									Новый
								</a>
							</div>
							<div class="main-menu-item" title="Только для демо!">
								<a class="main-menu-item-link-text" href="/addMoney">
									Пополнить счет
								</a>
							</div>
						<? endif ?>
					<? endif ?>
				</div>
			</div>

			<div class="main-content">
				%#main-content#%
			</div>

			<div class="footer"></div>
		</div>
	</body>

</html>