<html>
	<head>
		<title>Система заказов</title>
		<meta charset="utf-8"/>
		<link rel="stylesheet" href="/css/layout.css" />
		<link rel="stylesheet" href="/css/form.css" />
		<link rel="stylesheet" href="/css/order.css" />
		<link rel="stylesheet" href="/css/common.css" />

		<link rel="stylesheet" href="/css/jquery-ui.min.css"/>

		<script type="text/javascript" src="/js/jquery.js"></script>
		<script type="text/javascript" src="/js/jquery-ui.min.js"></script>
		<script type="text/javascript" src="/js/jquery.form.js"></script>
	</head>

	<body>
		<div class="container">
			<div class="header">
				<div class="logo">SFS</div>

				<div class="current-user">
					<div class="current-user-name">Василий Пупкин</div>
					<div class="current-user-logout-link">
						<a href="/logout">Выйти</a>
					</div>
				</div>
			</div>

			<div class="navigation-bar">
				<div class="main-menu">
					<div class="main-menu-item">
						<a class="main-menu-item-link-text" href="/">
							Заказы
						</a>
					</div>
					<div class="main-menu-item">
						<a class="main-menu-item-link-text" href="/new_order">
							Новый
						</a>
					</div>
				</div>
			</div>

			<div class="main-content">
				<? include('order/list.phtml') ?>
				<? include('order/add.phtml') ?>
			</div>
		</div>
	</body>

</html>