<div class="login-form-wrapper form-wrapper">
	<h3>Авторизация</h3>
	<form id="login-form" class="form" method="post" action="/auth">
		<div class="form-field">
			<div class="form-field-label">
				<label for="login-input">Логин:</label>
			</div>
			<div class="form-field-input">
				<input id="login-input" type="text" name="login" />
			</div>
		</div>

		<div class="form-field">
			<div class="form-field-label">
				<label for="password-input">Пароль:</label>
			</div>
			<div class="form-field-input">
				<input id="password-input" type="password" name="password" />
			</div>
		</div>

		<div class="form-field">
			<div class="form-submit">
				<input type="submit" value="Войти" />
			</div>
		</div>

		<div class="form-field">
		<span class="">Еще не с нами?</span> <a href="/join">Регистрация</a>
		</div>
	</form>
</div>